CREATE TABLE DEPT( 
DEPTNO NUMBER(2) NOT NULL,
DNAME VARCHAR2(14),
LOC VARCHAR2(13),
CONSTRAINT PK_DEPT PRIMARY KEY(DEPTNO),
CONSTRAINT Unique_DEPT UNIQUE (DNAME)
);

CREATE TABLE EMP(
EMPNO NUMBER(4) NOT NULL,
ENAME VARCHAR2(10),
JOB VARCHAR2(9),
MGR NUMBER(4),
HIREDATE DATE,
SAL NUMBER(7, 2),
COMM NUMBER(7, 2),
DEPTNO NUMBER(2),
CONSTRAINT PK_EMP PRIMARY KEY(EMPNO),
CONSTRAINT FK_EMP_DEPT FOREIGN KEY (DEPTNO) 
			      REFERENCES DEPT  (DEPTNO)
);
CREATE INDEX Idx_Ename  ON EMP(ENAME);


CREATE TABLE PRO(
PRONO NUMBER(4) NOT NULL,
PNAME VARCHAR2(10),
LOC VARCHAR2(13),
DEPTNO NUMBER(2),
CONSTRAINT PK_PRO PRIMARY KEY(PRONO),
CONSTRAINT FK_PRO_DEPT FOREIGN KEY (DEPTNO) 
			      REFERENCES DEPT  (DEPTNO)
);

CREATE TABLE EMPPRO(
EMPNO NUMBER(4) NOT NULL,
PRONO NUMBER(4) NOT NULL,
HOURS NUMBER(2),
CONSTRAINT FK_EMPPRO_EMP FOREIGN KEY (EMPNO) 
			          REFERENCES EMP (EMPNO),
CONSTRAINT FK_EMPPRO_PRONO FOREIGN KEY (PRONO) 
			           REFERENCES PRO  (PRONO)
);

-- Despues de Insertar los datos
-- ALTER TABLE EMP ADD CONSTRAINT FK_EMP_EMP FOREIGN KEY (MGR) REFERENCES EMP (EMPNO);
--