--
-- Table structure for table ciudades
--

-- primer nivel --

CREATE TABLE especialidades (
  IDESPECIALIDAD decimal(11,0) NOT NULL,
  DESCRIPCION varchar(30) DEFAULT NULL,
  PRIMARY KEY (IDESPECIALIDAD)
);


CREATE TABLE ciudades (
  IDCIUDAD decimal(11,0) PRIMARY KEY,
  DESCRIPCION varchar(30) DEFAULT NULL
);

-- 2 nivel ----


CREATE TABLE medicos (
  IDMEDICO varchar(10) NOT NULL,
  APELLIDOS varchar(50) DEFAULT NULL,
  NOMBRE varchar(50) DEFAULT NULL,
  IDESPECIALIDAD decimal(11,0) DEFAULT NULL,
  PRIMARY KEY (IDMEDICO),
  CONSTRAINT FK_MED_ESP FOREIGN KEY (IDESPECIALIDAD) REFERENCES especialidades (IDESPECIALIDAD)
);


CREATE TABLE pacientes (
  IDPACIENTE decimal(11,0) NOT NULL,
  APELLIDOS varchar(50) DEFAULT NULL,
  NOMBRE varchar(50) DEFAULT NULL,
  FECHA_NACIMIENTO datetime DEFAULT NULL,
  DIRECCION varchar(50) DEFAULT NULL,
  TELEFONO varchar(10) DEFAULT NULL,
  IDCIUDAD decimal(11,0) DEFAULT NULL,
  PRIMARY KEY (IDPACIENTE),
  KEY FK_PAC_CIU (IDCIUDAD),
  CONSTRAINT FK_PAC_CIU FOREIGN KEY (IDCIUDAD) REFERENCES ciudades (IDCIUDAD)  
);


--  3 nivel ----

CREATE TABLE citas (
  IDCITA decimal(11,0) NOT NULL,
  FECHA datetime DEFAULT NULL,
  IDMEDICO varchar(10) DEFAULT NULL,
  IDPACIENTE decimal(11,0) DEFAULT NULL,
  HABITACION decimal(11,0) DEFAULT NULL,
  CAMA varchar(1) DEFAULT NULL,
  PAGO decimal(10,2) DEFAULT NULL,
  PRIMARY KEY (IDCITA),
  KEY FK_CITAS_MED (IDMEDICO),
  KEY FK_CITAS_PAC (IDPACIENTE),
  CONSTRAINT FK_CITAS_MED FOREIGN KEY (IDMEDICO) REFERENCES medicos (IDMEDICO),
  CONSTRAINT FK_CITAS_PAC FOREIGN KEY (IDPACIENTE) REFERENCES pacientes (IDPACIENTE)  
);








